# Pages

"page 1":

  # Dossier

  Numero-dossier-MDPH: G1
  Annee-scolaire-debut: Q1
  Annee-scolaire-fin: S1
  Date-reunion_Jour: AG1
  Date-reunion_Mois: AI1
  Date-reunion_Annee: AK1

  # Eleve

  Nom-et-prenom-de-l-eleve: H3
  Nom-eleve: 
    cell: H3
    format: "{name!u} {firstname}"
    regex: ^(?P<name>.+)\s+(?P<firstname>.+)$
  Date-naissance_Jour: AG3
  Date-naissance_Mois: AI3 
  Date-naissance_Annee: AK3
  Numero-et-rue: D4 
  Ville: C5
  Code-postal: AF5
  Tel: C6
  Courriel: M6

  # Personne 1

  Personne1:
    cell: C10
    format: /{val}
    regex: (?P<val>.*)
  Personne1_Nom-ligne1: 
    cell: A11
    regex: ^([^\n]*)\n?
  Personne1_Nom-ligne2:    
    cell: A11
    regex: ^.*\n(.*)$
  Personne1_Numero-et-rue: D12
  Personne1_Code-postal: B13
  Personne1_Ville: F13
  Personne1_Telephone: C14
  Personne1_Courriel: D15
  
  # Personne 2

  Personne2:
    cell: O10
    format: /{val}
    regex: (?P<val>.*)
  Personne2_Nom-ligne1: 
    cell: M11
    regex: ^([^\n]*)\n?
  Personne2_Nom-ligne2:    
    cell: M11
    regex: ^.*\n(.*)$
  Personne2_Numero-et-rue: P12
  Personne2_Code-postal: N13
  Personne2_Ville: R13
  Personne2_Telephone: O14
  Personne2_Courriel: P15

  # Personne 3

  Personne3:
    cell: AA10
    format: /{val}
    regex: (?P<val>.*)
  Personne3_Nom-ligne1: 
    cell: Y11
    regex: ^([^\n]*)\n?
  Personne3_Nom-ligne2:    
    cell: Y11
    regex: ^.*\n(.*)$
  Personne3_Numero-et-rue: AB12
  Personne3_Code-postal: Z13
  Personne3_Ville: AD13
  Personne3_Telephone: AA14
  Personne3_Courriel: AB15

  # Points saillants liés à la scolarisation

  Coordonnees-enseignant_Nom: O18
  Coordonnees-enseignant_Telephone: C19
  Coordonnees-enseignant_Courriel: L19
  Etablissement-scolaire: I20
  Classe-frequentee: AD20
  Etablissement-scolaire_Numero-et-rue: D21
  Etablissement-scolaire_Ville: C22
  Points-saillants-scolarisation_Code-postal: AC22

  # Parcours de scolarisation

  Parcours-de-scolarisation_Annee1: A25
  Parcours-de-scolarisation_Scolarisation1: E25
  Parcours-de-scolarisation_Annee2: A26
  Parcours-de-scolarisation_Scolarisation2: E26
  Parcours-de-scolarisation_Annee3: A27
  Parcours-de-scolarisation_Scolarisation3: E27
  Parcours-de-scolarisation_Annee4: A28
  Parcours-de-scolarisation_Scolarisation4: E28
  Parcours-de-scolarisation_Annee5: A29
  Parcours-de-scolarisation_Scolarisation5: E29
  Parcours-de-scolarisation_Annee6: A30
  Parcours-de-scolarisation_Scolarisation6: E30